from magic_agents.models.factory.Nodes.BaseNodeModel import ModelAgentFlowTypesModel
from magic_agents.models.factory.Nodes.ClientNodeModel import ClientNodeModel
from magic_agents.models.factory.Nodes.FetchNodeModel import FetchNodeModel
from magic_agents.models.factory.Nodes.LlmNodeModel import LlmNodeModel
from magic_agents.models.factory.Nodes.ParserNodeModel import ParserNodeModel
from magic_agents.models.factory.Nodes.SendMessageNodeModel import SendMessageNodeModel
from magic_agents.models.factory.Nodes.TextNodeModel import TextNodeModel
from magic_agents.models.factory.Nodes.UserInputNodeModel import UserInputNodeModel
from magic_agents.models.factory.Nodes.LoopNodeModel import LoopNodeModel
from magic_agents.models.factory.Nodes.InnerNodeModel import InnerNodeModel
