"""
EdgeNodeModel - Represents an edge connection between nodes in a flow graph.

This model defines the connection between source and target nodes via handles.
Edges now support optional port identity (sourcePort/targetPort) alongside
handles, preserving backward compatibility.

Key change: Edge.id is now unique per edge instance (UUID-generated by default),
enabling edge-level tracking for fan-in scenarios.
"""
import uuid
from typing import Optional

from pydantic import BaseModel, Field


class EdgeNodeModel(BaseModel):
    """
    Edge connection model between nodes.
    
    Attributes:
        id: Unique edge identifier (UUID by default). Required for edge-level
            tracking in NodeInputTracker. Preserved through serialization.
        source: Source node ID
        target: Target node ID (optional for special cases like VOID)
        sourceHandle: Output handle on source node (backward-compatible alias)
        targetHandle: Input handle on target node (backward-compatible alias)
        sourcePort: Optional stable port identity (authoritative when present)
        targetPort: Optional stable port identity (authoritative when present)
    """
    # Unique ID per edge instance - critical for fan-in tracking
    id: str = Field(default_factory=lambda: uuid.uuid4().hex)
    source: str
    target: Optional[str] = None
    sourceHandle: Optional[str] = None
    targetHandle: Optional[str] = None
    # Optional port identity fields (Phase 1 - backward compat)
    sourcePort: Optional[str] = None
    targetPort: Optional[str] = None
