"""
EdgeNodeModel - Represents an edge connection between nodes in a flow graph.

This model defines the connection between source and target nodes via handles.
Edges now support optional port identity (sourcePort/targetPort) alongside
handles, preserving backward compatibility.

Key change: Edge.id is now unique per edge instance (UUID-generated by default),
enabling edge-level tracking for fan-in scenarios.

Phase 8.2: Added EdgeHookConfig and EdgeNodeModel.hooks field for edge-level
hook configuration. A hook attached to an edge fires when output propagates
through that edge to the target node.
"""
import uuid
from typing import Optional

from pydantic import BaseModel, Field


class EdgeHookConfig(BaseModel):
    """Configuration for edge-level hooks.

    Attached to EdgeNodeModel.hooks field. Defines a NodeHook that
    can be invoked when output propagates through this edge.

    Attributes:
        hook_node_id: NodeHook node ID to invoke when edge is traversed.
        hook_type: Hook event type identifier (default: "on_edge_traversed").
        timeout_override: Optional timeout override in seconds.
        enabled: Whether this hook is active (default: True).
    """
    hook_node_id: Optional[str] = Field(
        default=None,
        description="NodeHook node ID to invoke when edge is traversed"
    )
    hook_type: str = Field(
        default="on_edge_traversed",
        description="Hook event type identifier"
    )
    timeout_override: Optional[int] = Field(
        default=None,
        description="Timeout override in seconds"
    )
    enabled: bool = Field(
        default=True,
        description="Whether this hook is active"
    )


class EdgeNodeModel(BaseModel):
    """
    Edge connection model between nodes.

    Attributes:
        id: Unique edge identifier (UUID by default). Required for edge-level
            tracking in NodeInputTracker. Preserved through serialization.
        source: Source node ID
        target: Target node ID (optional for special cases like VOID)
        sourceHandle: Output handle on source node (backward-compatible alias)
        targetHandle: Input handle on target node (backward-compatible alias)
        sourcePort: Optional stable port identity (authoritative when present)
        targetPort: Optional stable port identity (authoritative when present)
        hooks: Optional EdgeHookConfig for edge-level hook configuration.
    """
    # Unique ID per edge instance - critical for fan-in tracking
    id: str = Field(default_factory=lambda: uuid.uuid4().hex)
    source: str
    target: Optional[str] = None
    sourceHandle: Optional[str] = None
    targetHandle: Optional[str] = None
    # Optional port identity fields (Phase 1 - backward compat)
    sourcePort: Optional[str] = None
    targetPort: Optional[str] = None
    # Phase 8.2: Edge-level hook configuration
    hooks: Optional[EdgeHookConfig] = Field(
        default=None,
        description="Optional edge-level hook configuration"
    )
